spring:
  profiles: dev
eureka:
  instance:
    hostname: dev
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10008/eureka
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    peer-eureka-nodes-update-interval-ms: 10000
    enable-self-preservation: true
age: 22
Name: zhaohongchengss